// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Agonist Development AB
/**
 * Disclosure wording per language.
 *
 * Article 50(5) requires the information to be clear, distinguishable and
 * accessible, provided at the latest at the time of the first interaction or
 * exposure. Nothing in the Regulation prescribes a sentence, so these strings
 * are a defensible default, not a safe harbour: a deployer serving a given
 * market should have counsel read the wording it ships.
 *
 * Translations are plain and formal by design. A disclosure that reads as
 * marketing copy defeats the "clear and distinguishable" requirement.
 */

/** Languages shipped in this release. */
export const LOCALES = ["en", "de", "fr", "es", "it", "sv"] as const;

export type Locale = (typeof LOCALES)[number];

/** The distinct notices the SDK can render. */
export interface DisclosureStrings {
  /** 50(1) — first-interaction notice. */
  interaction: string;
  /** 50(1) — periodic restatement in a long-running conversation. */
  interactionReminder: string;
  /** 50(1) — short prefix for a single chat turn, where a banner is unavailable. */
  interactionPrefix: string;
  /** 50(3) — emotion recognition in operation. */
  emotionRecognition: string;
  /** 50(3) — biometric categorisation in operation. */
  biometricCategorisation: string;
  /** 50(4) — deepfake image, audio or video. */
  deepfake: string;
  /** 50(4) — AI-generated text published on a matter of public interest. */
  syntheticText: string;
  /** 50(4) — reduced form for an evidently artistic, creative, satirical or fictional work. */
  artisticWork: string;
  /** 50(2) — human-readable companion to the machine-readable mark. */
  syntheticMarking: string;
}

export const DISCLOSURES: Record<Locale, DisclosureStrings> = {
  en: {
    interaction: "You are interacting with an AI system.",
    interactionReminder: "Reminder: you are interacting with an AI system.",
    interactionPrefix: "AI",
    emotionRecognition:
      "This system uses emotion recognition. You are being informed of its operation.",
    biometricCategorisation:
      "This system uses biometric categorisation. You are being informed of its operation.",
    deepfake: "This image, audio or video has been artificially generated or manipulated.",
    syntheticText: "This text was generated by an AI system.",
    artisticWork: "This work contains artificially generated or manipulated content.",
    syntheticMarking: "Artificially generated or manipulated content.",
  },
  de: {
    interaction: "Sie interagieren mit einem KI-System.",
    interactionReminder: "Hinweis: Sie interagieren mit einem KI-System.",
    interactionPrefix: "KI",
    emotionRecognition:
      "Dieses System verwendet Emotionserkennung. Sie werden hiermit über den Betrieb informiert.",
    biometricCategorisation:
      "Dieses System verwendet biometrische Kategorisierung. Sie werden hiermit über den Betrieb informiert.",
    deepfake: "Dieses Bild, diese Audio- oder Videoaufnahme wurde künstlich erzeugt oder manipuliert.",
    syntheticText: "Dieser Text wurde von einem KI-System erzeugt.",
    artisticWork: "Dieses Werk enthält künstlich erzeugte oder manipulierte Inhalte.",
    syntheticMarking: "Künstlich erzeugter oder manipulierter Inhalt.",
  },
  fr: {
    interaction: "Vous interagissez avec un système d'IA.",
    interactionReminder: "Rappel : vous interagissez avec un système d'IA.",
    interactionPrefix: "IA",
    emotionRecognition:
      "Ce système utilise la reconnaissance des émotions. Vous êtes informé de son fonctionnement.",
    biometricCategorisation:
      "Ce système utilise la catégorisation biométrique. Vous êtes informé de son fonctionnement.",
    deepfake: "Cette image, cet enregistrement audio ou cette vidéo a été généré ou manipulé artificiellement.",
    syntheticText: "Ce texte a été généré par un système d'IA.",
    artisticWork: "Cette œuvre contient des contenus générés ou manipulés artificiellement.",
    syntheticMarking: "Contenu généré ou manipulé artificiellement.",
  },
  es: {
    interaction: "Está interactuando con un sistema de IA.",
    interactionReminder: "Recordatorio: está interactuando con un sistema de IA.",
    interactionPrefix: "IA",
    emotionRecognition:
      "Este sistema utiliza reconocimiento de emociones. Se le informa de su funcionamiento.",
    biometricCategorisation:
      "Este sistema utiliza categorización biométrica. Se le informa de su funcionamiento.",
    deepfake: "Esta imagen, audio o vídeo ha sido generado o manipulado artificialmente.",
    syntheticText: "Este texto ha sido generado por un sistema de IA.",
    artisticWork: "Esta obra contiene contenido generado o manipulado artificialmente.",
    syntheticMarking: "Contenido generado o manipulado artificialmente.",
  },
  it: {
    interaction: "Sta interagendo con un sistema di IA.",
    interactionReminder: "Promemoria: sta interagendo con un sistema di IA.",
    interactionPrefix: "IA",
    emotionRecognition:
      "Questo sistema utilizza il riconoscimento delle emozioni. È informato del suo funzionamento.",
    biometricCategorisation:
      "Questo sistema utilizza la categorizzazione biometrica. È informato del suo funzionamento.",
    deepfake: "Questa immagine, questo audio o questo video è stato generato o manipolato artificialmente.",
    syntheticText: "Questo testo è stato generato da un sistema di IA.",
    artisticWork: "Quest'opera contiene contenuti generati o manipolati artificialmente.",
    syntheticMarking: "Contenuto generato o manipolato artificialmente.",
  },
  sv: {
    interaction: "Du interagerar med ett AI-system.",
    interactionReminder: "Påminnelse: du interagerar med ett AI-system.",
    interactionPrefix: "AI",
    emotionRecognition:
      "Detta system använder känsloigenkänning. Du informeras härmed om dess drift.",
    biometricCategorisation:
      "Detta system använder biometrisk kategorisering. Du informeras härmed om dess drift.",
    deepfake: "Denna bild, detta ljud eller denna video har genererats eller manipulerats artificiellt.",
    syntheticText: "Denna text har genererats av ett AI-system.",
    artisticWork: "Detta verk innehåller artificiellt genererat eller manipulerat innehåll.",
    syntheticMarking: "Artificiellt genererat eller manipulerat innehåll.",
  },
};

/** Whether a string is one of the shipped locales. */
export function isLocale(value: string): value is Locale {
  return (LOCALES as readonly string[]).includes(value);
}

/**
 * Pick the closest shipped locale for a language tag, falling back to English.
 * "de-AT" resolves to "de"; an unshipped language resolves to "en".
 */
export function resolveLocale(tag: string | undefined): Locale {
  if (!tag) return "en";
  const primary = tag.toLowerCase().split("-")[0] ?? "";
  return isLocale(primary) ? primary : "en";
}
